services:
  eumaster4hpc:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"

  eumaster4hpc-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - "./jupyter:/jupyter"
    profiles:
      - dev
